# Generated by Django 4.2.5 on 2023-09-06 17:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        help_text='Customer',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='customer',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='customer',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='DealPacket',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text='Created at',
                        verbose_name='created_at',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Deal Packet',
                'verbose_name_plural': 'Deal Packets',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Gem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Name of gem',
                        max_length=100,
                        unique=True,
                        verbose_name='name',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Gem',
                'verbose_name_plural': 'Gems',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'total',
                    models.PositiveIntegerField(
                        help_text="Deal's total price",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name='total_price',
                    ),
                ),
                (
                    'quantity',
                    models.PositiveSmallIntegerField(
                        help_text='Quantity of gems',
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name='quantity',
                    ),
                ),
                (
                    'date',
                    models.DateTimeField(
                        help_text='Date and time of deal',
                        verbose_name='date',
                    ),
                ),
                (
                    'customer',
                    models.ForeignKey(
                        help_text="Deal's customer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='deals',
                        to='gems.customer',
                        verbose_name='deal',
                    ),
                ),
                (
                    'gem',
                    models.ForeignKey(
                        help_text='Gem name',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='deals',
                        to='gems.gem',
                        verbose_name='item',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ('-pk',),
            },
        ),
    ]
